service: task-time-attack

provider:
  name: aws
  iamManagedPolicies:
    - 'arn:aws:iam::aws:policy/AmazonSQSFullAccess'
  endpointType: REGIONAL
  runtime: ruby2.5
  stage: dev
  region: ap-northeast-1
  deploymentBucket:
    name: task-time-attack-deploy-bucket
  environment:
    # env:VARIABLE でローカルの環境変数の値をセット
    SLACK_VERIFICATION_TOKEN: '${env:SLACK_VERIFICATION_TOKEN}'
    SLACK_APP_ID: '${env:SLACK_APP_ID}'
    SLACK_BOT_TOKEN: '${env:SLACK_BOT_TOKEN}'
    SLACK_USER_TOKEN: '${env:SLACK_USER_TOKEN}'
    AWS_SQS_URL:
      # CloudFormationの論理名をRefで参照することでSQSのURLを取得
      Ref: taskTimeAttackSqs # customを使って変数にすると良さそう

resources:
  # 　Resources以下はCloudFormationの構文
  Resources:
    taskTimeAttackSqs:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'taskTimeAttackSqs'

# package:

functions:
  task-time-attack-http-function:
    name: task-time-attack-http-function
    handler: handler.hello
    events:
      - http:
          path: slack/task_time_attack
          method: post
          integration: lambda

  task-time-attack-sqs-function:
    name: task-time-attack-sqs-function
    handler: index.handlerSqs
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - taskTimeAttackSqs
              - Arn
          batchSize: 1 # メッセージは1通ずつ読み取る